import {useEffect,useState} from "react";
import {FaChevronRight,FaExternalLinkAlt,FaInstagram,FaMapMarkerAlt,FaStar} from "react-icons/fa";
import {getPublicDigitalMenu,getPublicDigitalMenus,trackEvent} from "../lib/supabaseRest";
import "./DigitalMenu.css";
const CAFE={bg:"#171717",panel:"#202020",panel2:"#292929",accent:"#e51b23",accent2:"#b80f17",cream:"#fff7ed",gold:"#f4c542"};
const THEMES={"Cafe Rio":CAFE,"Classic Red":{bg:"#fff7f5",panel:"#fff",panel2:"#f9e7e4",accent:"#c62828",accent2:"#a51e1e",cream:"#30100d",gold:"#b67a00"},"Emerald":{bg:"#10251e",panel:"#17352b",panel2:"#21483a",accent:"#43a56f",accent2:"#2c8053",cream:"#f4fff8",gold:"#d9c47a"},"Midnight Gold":{bg:"#111318",panel:"#1b1e25",panel2:"#252a34",accent:"#d6aa45",accent2:"#aa7f24",cream:"#faf7ef",gold:"#f0c967"}};
export default function DigitalMenu({businessSlug,menuSlug}){
 const [data,setData]=useState(null),[list,setList]=useState(null),[active,setActive]=useState(""),[error,setError]=useState(""),[loading,setLoading]=useState(true);
 useEffect(()=>{let live=true;(async()=>{try{if(menuSlug){const d=await getPublicDigitalMenu(businessSlug,menuSlug);if(!d)throw new Error("Menu unavailable.");if(live){setData(d);trackEvent(d.business_id,"digital_menu_view").catch(()=>{})}}else{const d=await getPublicDigitalMenus(businessSlug);if(!d)throw new Error("Restaurant not found.");if(live)setList(d)}}catch(e){if(live)setError(e.message||"Menu unavailable.")}finally{if(live)setLoading(false)}})();return()=>{live=false}},[businessSlug,menuSlug]);
 if(loading)return <main className="digital-menu-page"><div className="digital-menu-state">Loading menu…</div></main>;
 if(!menuSlug&&list){const menus=list.menus||[];return <main className="digital-menu-page" style={{"--dm-bg":CAFE.bg,"--dm-panel":CAFE.panel,"--dm-panel2":CAFE.panel2,"--dm-accent":CAFE.accent,"--dm-accent2":CAFE.accent2,"--dm-cream":CAFE.cream,"--dm-gold":CAFE.gold}}><div className="digital-menu-shell selector"><div className="selector-brand"><strong>{list.business_name}</strong><span>CHOOSE A MENU</span></div><h1>What would you like to explore?</h1><div className="menu-selector-list">{menus.map(m=><a key={m.id} href={`/m/${businessSlug}/${m.slug}`}><div>{m.logo_url?<img src={m.logo_url} alt=""/>:<span className="selector-icon">🍽</span>}</div><section><strong>{m.title}</strong><small>{m.subtitle||"View menu"}</small></section><FaChevronRight/></a>)}</div><footer className="dm-footer">POWERED BY HAKI <FaExternalLinkAlt/></footer></div></main>}
 if(error||!data)return <main className="digital-menu-page"><div className="digital-menu-state"><h1>Menu unavailable</h1><p>{error||"This menu could not be found."}</p></div></main>;
 const m=data.menu,d=m.details||{},theme=THEMES[m.theme?.preset]||CAFE,cats=(m.menu_data?.categories||[]).filter(c=>(c.items||[]).some(i=>i.available!==false)),selected=cats.find(c=>c.name===active)||cats[0];
 const style={"--dm-bg":theme.bg,"--dm-panel":theme.panel,"--dm-panel2":theme.panel2,"--dm-accent":theme.accent,"--dm-accent2":theme.accent2,"--dm-cream":theme.cream,"--dm-gold":theme.gold};
 return <main className="digital-menu-page" style={style}><div className="digital-menu-shell">{m.banner_url&&<header className="digital-menu-hero"><img src={m.banner_url} alt=""/></header>}<div className="digital-menu-content">{m.logo_url&&<div className="digital-menu-logo"><img src={m.logo_url} alt={m.title}/></div>}<h1>{m.title}</h1>{m.subtitle&&<div className="digital-menu-tagline">{m.subtitle}</div>}{d.tagline&&<div className="digital-menu-tagline">{d.tagline}</div>}<div className="digital-menu-actions">{d.googleReviewUrl&&<a className="dm-btn primary" href={d.googleReviewUrl} target="_blank" rel="noreferrer"><FaStar/> Rate us on Google</a>}{d.mapUrl&&<a className="dm-btn" href={d.mapUrl} target="_blank" rel="noreferrer"><FaMapMarkerAlt/> Find us</a>}{d.instagramUrl&&<a className="dm-btn" href={d.instagramUrl} target="_blank" rel="noreferrer"><FaInstagram/> Instagram</a>}</div>{d.story&&<section className="dm-section"><div className="dm-section-title">Our Story</div><p className="dm-story">{d.story}</p></section>}{Array.isArray(d.galleryImages)&&d.galleryImages.filter(Boolean).length>0&&<section className="dm-section dm-gallery-section"><div className="dm-section-title">Ambience & Upcoming Events</div><div className="dm-gallery">{d.galleryImages.filter(Boolean).map((url,index)=><img key={`${url}-${index}`} src={url} alt={`Restaurant ambience ${index+1}`} loading="lazy"/>)}</div></section>}<section className="dm-section"><div className="dm-section-title">Menu</div>{cats.length>1&&<div className="dm-tabs">{cats.map(c=><button key={c.id||c.name} className={selected?.name===c.name?"active":""} onClick={()=>setActive(c.name)}>{c.name}</button>)}</div>}<div className="dm-items">{selected?<><h2>{selected.name}</h2>{(selected.items||[]).filter(i=>i.available!==false).map((i,n)=><article className="dm-item" key={`${i.id||i.name}-${n}`}><div><strong>{i.name}</strong>{i.description&&<p>{i.description}</p>}</div>{i.price&&<span>{i.price}</span>}</article>)}</>:<div className="dm-empty">No menu items are available yet.</div>}</div></section><footer className="dm-footer">POWERED BY HAKI <FaExternalLinkAlt/></footer></div></div></main>;
}
