import { useEffect, useMemo, useState } from "react";
import { FaCheck, FaExternalLinkAlt, FaPlus, FaTrash, FaArrowUp, FaArrowDown, FaSave, FaUtensils } from "react-icons/fa";
import { getDigitalMenuAdminByToken, saveDigitalMenuByToken } from "../lib/supabaseRest";
import "./MenuAdmin.css";

const DAYS = ["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"];
const EMPTY_HOURS = DAYS.map(day => ({ day, open: "10:00", close: "22:00", closed: false }));
const EMPTY_MENU = { title: "", subtitle: "", categories: [] };
const EMPTY_DETAILS = { tagline: "", story: "", address: "", mapUrl: "", instagramUrl: "", googleReviewUrl: "" };
function uid(){return crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`}
function blankCategory(){return{id:uid(),name:"New Category",items:[]}}
function blankItem(){return{id:uid(),name:"New Item",description:"",price:"",available:true}}

export default function MenuAdmin(){
 const token=useMemo(()=>window.location.pathname.split("/").filter(Boolean)[1]||"",[]);
 const [business,setBusiness]=useState(null),[menu,setMenu]=useState(EMPTY_MENU),[hours,setHours]=useState(EMPTY_HOURS),[details,setDetails]=useState(EMPTY_DETAILS),[tab,setTab]=useState("menu"),[preview,setPreview]=useState(false),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[message,setMessage]=useState(""),[error,setError]=useState("");
 useEffect(()=>{let alive=true;(async()=>{try{const data=await getDigitalMenuAdminByToken(token);if(!alive)return;setBusiness(data);setMenu({...EMPTY_MENU,...(data.digital_menu||{})});setHours(Array.isArray(data.digital_menu_hours)&&data.digital_menu_hours.length?data.digital_menu_hours:EMPTY_HOURS);setDetails({...EMPTY_DETAILS,...(data.digital_menu_details||{})})}catch(err){if(alive)setError(err.message||"This menu link is invalid or unavailable.")}finally{if(alive)setLoading(false)}})();return()=>{alive=false}},[token]);
 const save=async()=>{setSaving(true);setMessage("");setError("");try{await saveDigitalMenuByToken(token,{digital_menu:menu,digital_menu_hours:hours,digital_menu_details:details,digital_menu_enabled:true});setMessage("Changes saved.")}catch(err){setError(err.message||"Could not save changes.")}finally{setSaving(false)}};
 const updateCategory=(id,patch)=>setMenu(m=>({...m,categories:m.categories.map(c=>c.id===id?{...c,...patch}:c)}));
 const removeCategory=id=>setMenu(m=>({...m,categories:m.categories.filter(c=>c.id!==id)}));
 const moveCategory=(i,d)=>setMenu(m=>{const a=[...m.categories],n=i+d;if(n<0||n>=a.length)return m;[a[i],a[n]]=[a[n],a[i]];return{...m,categories:a}});
 const addCategory=()=>setMenu(m=>({...m,categories:[...m.categories,blankCategory()]}));
 const addItem=id=>updateCategory(id,{items:[...(menu.categories.find(c=>c.id===id)?.items||[]),blankItem()]});
 const updateItem=(cid,iid,patch)=>updateCategory(cid,{items:(menu.categories.find(c=>c.id===cid)?.items||[]).map(i=>i.id===iid?{...i,...patch}:i)});
 const removeItem=(cid,iid)=>updateCategory(cid,{items:(menu.categories.find(c=>c.id===cid)?.items||[]).filter(i=>i.id!==iid)});
 const moveItem=(cid,i,d)=>{const c=menu.categories.find(x=>x.id===cid);if(!c)return;const a=[...c.items],n=i+d;if(n<0||n>=a.length)return;[a[i],a[n]]=[a[n],a[i]];updateCategory(cid,{items:a})};
 if(loading)return <main className="menu-admin-page"><div className="menu-admin-loading">Loading menu admin…</div></main>;
 if(error||!business)return <main className="menu-admin-page"><div className="menu-admin-error"><h1>Menu Admin</h1><p>{error||"Menu not found."}</p></div></main>;
 return <main className="menu-admin-page">
  <header className="menu-admin-top"><div><strong>{business.business_name}</strong><span>OWNER ADMIN PANEL</span></div><div className="menu-admin-top-actions"><a href={`/p/${business.slug}`} target="_blank" rel="noreferrer">View Profile <FaExternalLinkAlt/></a><button onClick={save} disabled={saving}>{saving?<FaSave/>:<FaCheck/>} {saving?"Saving…":"Save Changes"}</button></div></header>
  <div className="menu-admin-layout"><nav className="menu-admin-nav">{[["menu","Menu"],["hours","Working Hours"],["branding","Logo & Banner"],["details","Restaurant Details"],["backup","Backup"]].map(([id,label])=><button key={id} className={tab===id?"active":""} onClick={()=>setTab(id)}>{label}</button>)}</nav>
   <section className="menu-admin-content">
    {tab==="menu"&&<><div className="menu-admin-heading"><div><h1>Menu</h1><p>Add, edit, remove and reorder categories and dishes.</p></div><button className="menu-admin-primary" onClick={addCategory}><FaPlus/> Add Category</button></div><div className="menu-field-grid"><label>Menu title<input value={menu.title} onChange={e=>setMenu({...menu,title:e.target.value})} placeholder={`${business.business_name} Menu`}/></label><label>Subtitle<input value={menu.subtitle} onChange={e=>setMenu({...menu,subtitle:e.target.value})} placeholder="Fresh menu · prices can be updated anytime"/></label></div><div className="menu-categories">{menu.categories.length===0&&<div className="menu-empty"><FaUtensils/><strong>No categories yet</strong><span>Start by adding your first category.</span></div>}{menu.categories.map((c,ci)=><article className="menu-category" key={c.id}><div className="menu-category-head"><input value={c.name} onChange={e=>updateCategory(c.id,{name:e.target.value})}/><div><button onClick={()=>moveCategory(ci,-1)} disabled={ci===0}><FaArrowUp/></button><button onClick={()=>moveCategory(ci,1)} disabled={ci===menu.categories.length-1}><FaArrowDown/></button><button className="danger" onClick={()=>removeCategory(c.id)}><FaTrash/></button></div></div><div className="menu-items-editor">{c.items.map((item,ii)=><div className="menu-item-row" key={item.id}><div className="menu-item-fields"><input value={item.name} onChange={e=>updateItem(c.id,item.id,{name:e.target.value})} placeholder="Item name"/><input value={item.description} onChange={e=>updateItem(c.id,item.id,{description:e.target.value})} placeholder="Description"/><input value={item.price} onChange={e=>updateItem(c.id,item.id,{price:e.target.value})} placeholder="₹299"/><label className="availability"><input type="checkbox" checked={item.available!==false} onChange={e=>updateItem(c.id,item.id,{available:e.target.checked})}/> Available</label></div><div className="menu-item-actions"><button onClick={()=>moveItem(c.id,ii,-1)} disabled={ii===0}><FaArrowUp/></button><button onClick={()=>moveItem(c.id,ii,1)} disabled={ii===c.items.length-1}><FaArrowDown/></button><button className="danger" onClick={()=>removeItem(c.id,item.id)}><FaTrash/></button></div></div>)}</div><button className="menu-add-item" onClick={()=>addItem(c.id)}><FaPlus/> Add Dish</button></article>)}</div></>}
    {tab==="hours"&&<div className="menu-admin-card"><h1>Working Hours</h1><p>Update the hours shown on the digital menu.</p>{hours.map((h,i)=><div className="hours-row" key={h.day}><strong>{h.day}</strong><label><input type="checkbox" checked={!h.closed} onChange={e=>setHours(x=>x.map((v,j)=>j===i?{...v,closed:!e.target.checked}:v))}/> Open</label><input type="time" value={h.open} disabled={h.closed} onChange={e=>setHours(x=>x.map((v,j)=>j===i?{...v,open:e.target.value}:v))}/><span>to</span><input type="time" value={h.close} disabled={h.closed} onChange={e=>setHours(x=>x.map((v,j)=>j===i?{...v,close:e.target.value}:v))}/></div>)}</div>}
    {tab==="branding"&&<div className="menu-admin-card"><h1>Logo & Banner</h1><p>The digital menu uses the existing Haki business branding.</p><div className="branding-preview"><div><span>Logo</span>{business.logo_url?<img src={business.logo_url} alt="Business logo"/>:<div className="no-image">No logo</div>}</div><div><span>Banner</span>{business.banner_url?<img src={business.banner_url} alt="Business banner"/>:<div className="no-image">No banner</div>}</div></div><p className="menu-note">Branding uploads remain controlled from Haki Business Profile for now.</p></div>}
    {tab==="details"&&<div className="menu-admin-card"><h1>Restaurant Details</h1><p>These details belong to the digital menu experience.</p><label>Tagline<input value={details.tagline} onChange={e=>setDetails({...details,tagline:e.target.value})} placeholder="Italian Breeze · Pure Veg"/></label><label>Restaurant story<textarea value={details.story} onChange={e=>setDetails({...details,story:e.target.value})} rows="5" placeholder="Tell customers about the restaurant..."/></label><label>Address<input value={details.address} onChange={e=>setDetails({...details,address:e.target.value})}/></label><div className="menu-field-grid"><label>Google Maps URL<input value={details.mapUrl} onChange={e=>setDetails({...details,mapUrl:e.target.value})}/></label><label>Instagram URL<input value={details.instagramUrl} onChange={e=>setDetails({...details,instagramUrl:e.target.value})}/></label></div><label>Google Review URL<input value={details.googleReviewUrl} onChange={e=>setDetails({...details,googleReviewUrl:e.target.value})}/></label></div>}
    {tab==="backup"&&<div className="menu-admin-card"><h1>Backup</h1><p>Keep a copy of this digital menu before making major changes.</p><div className="backup-actions"><button onClick={()=>{const blob=new Blob([JSON.stringify({menu,hours,details},null,2)],{type:"application/json"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=`${business.slug}-menu-backup.json`;a.click();URL.revokeObjectURL(url)}}>Export Menu Backup</button><label className="backup-import">Import Backup<input type="file" accept="application/json" onChange={async e=>{const file=e.target.files?.[0];if(!file)return;try{const data=JSON.parse(await file.text());if(data.menu)setMenu({...EMPTY_MENU,...data.menu});if(Array.isArray(data.hours))setHours(data.hours);if(data.details)setDetails({...EMPTY_DETAILS,...data.details});setMessage("Backup loaded. Click Save Changes to apply it.")}catch{setError("Invalid backup file.")}}}/></label></div></div>}
    <div className="menu-admin-bottom"><button className="menu-admin-secondary" onClick={()=>setPreview(true)}>Preview Digital Menu</button><button className="menu-admin-primary" onClick={save} disabled={saving}><FaCheck/> {saving?"Saving…":"Save Changes"}</button></div>{message&&<div className="menu-admin-success"><FaCheck/> {message}</div>}{error&&<div className="menu-admin-error">{error}</div>}
   </section>
  </div>
  {preview&&<div className="menu-preview-overlay" onClick={e=>e.target===e.currentTarget&&setPreview(false)}><div className="menu-preview"><button className="preview-close" onClick={()=>setPreview(false)}>×</button><div className="preview-hero">{business.banner_url&&<img src={business.banner_url} alt=""/>}</div><div className="preview-body">{business.logo_url&&<img className="preview-logo" src={business.logo_url} alt=""/>}<h2>{business.business_name}</h2><p>{details.tagline}</p><div className="preview-hours">{hours.filter(h=>!h.closed).map(h=><span key={h.day}>{h.day.slice(0,3)} {h.open}–{h.close}</span>)}</div><h3>{menu.title||`${business.business_name} Menu`}</h3><small>{menu.subtitle}</small>{menu.categories.map(c=><section key={c.id}><h4>{c.name}</h4>{c.items.filter(i=>i.available!==false).map(i=><div className="preview-item" key={i.id}><div><strong>{i.name}</strong><span>{i.description}</span></div><b>{i.price}</b></div>)}</section>)}</div></div></div>}
 </main>
}
